language: python

python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'
  - '3.5'

install:
  - pip install -r test_requirements.txt
  - pip install ordereddict unittest2

script:
  - nosetests
  - python -m doctest patterndict.py
